export const media = {
  "caballos": {
    "photos": [
      "/caballos/photos/caballos-photo-001.jpeg",
      "/caballos/photos/caballos-photo-002.jpeg",
      "/caballos/photos/caballos-photo-003.jpeg",
      "/caballos/photos/caballos-photo-004.jpeg",
      "/caballos/photos/caballos-photo-005.jpeg",
      "/caballos/photos/caballos-photo-006.jpeg",
      "/caballos/photos/caballos-photo-007.jpeg",
      "/caballos/photos/caballos-photo-008.jpeg",
      "/caballos/photos/caballos-photo-009.jpeg",
      "/caballos/photos/caballos-photo-010.jpeg",
      "/caballos/photos/caballos-photo-011.jpeg",
      "/caballos/photos/caballos-photo-012.jpeg",
      "/caballos/photos/caballos-photo-013.jpeg",
      "/caballos/photos/caballos-photo-014.jpeg",
      "/caballos/photos/caballos-photo-015.jpeg",
      "/caballos/photos/caballos-photo-016.jpeg",
      "/caballos/photos/caballos-photo-017.jpeg",
      "/caballos/photos/caballos-photo-018.jpeg",
      "/caballos/photos/caballos-photo-019.jpeg",
      "/caballos/photos/caballos-photo-020.jpeg",
      "/caballos/photos/caballos-photo-021.jpeg",
      "/caballos/photos/caballos-photo-022.jpeg",
      "/caballos/photos/caballos-photo-023.jpeg",
      "/caballos/photos/caballos-photo-024.jpeg",
      "/caballos/photos/caballos-photo-025.jpeg",
      "/caballos/photos/caballos-photo-026.jpeg",
      "/caballos/photos/caballos-photo-027.jpeg",
      "/caballos/photos/caballos-photo-028.jpeg",
      "/caballos/photos/caballos-photo-029.jpeg",
      "/caballos/photos/caballos-photo-030.jpeg",
      "/caballos/photos/caballos-photo-031.jpeg",
      "/caballos/photos/caballos-photo-032.jpeg",
      "/caballos/photos/caballos-photo-033.jpeg",
      "/caballos/photos/caballos-photo-034.jpeg",
      "/caballos/photos/caballos-photo-035.jpeg"
    ],
    "videos": []
  },
  "cenotes": {
    "photos": [
      "/cenotes/photos/cenotes-photo-001.jpeg",
      "/cenotes/photos/cenotes-photo-002.jpeg",
      "/cenotes/photos/cenotes-photo-003.jpeg",
      "/cenotes/photos/cenotes-photo-004.jpeg",
      "/cenotes/photos/cenotes-photo-005.jpeg",
      "/cenotes/photos/cenotes-photo-006.jpeg",
      "/cenotes/photos/cenotes-photo-007.jpeg",
      "/cenotes/photos/cenotes-photo-008.jpeg",
      "/cenotes/photos/cenotes-photo-009.jpeg"
    ],
    "videos": [
      "/cenotes/videos/cenotes-video-001.mp4",
      "/cenotes/videos/cenotes-video-002.mp4"
    ]
  },
  "habitaciones": {
    "photos": [
      "/habitaciones/photos/habitaciones-photo-001.jpeg",
      "/habitaciones/photos/habitaciones-photo-002.jpeg",
      "/habitaciones/photos/habitaciones-photo-003.jpeg",
      "/habitaciones/photos/habitaciones-photo-004.jpeg",
      "/habitaciones/photos/habitaciones-photo-005.jpeg",
      "/habitaciones/photos/habitaciones-photo-006.jpeg",
      "/habitaciones/photos/habitaciones-photo-007.jpeg",
      "/habitaciones/photos/habitaciones-photo-008.jpeg",
      "/habitaciones/photos/habitaciones-photo-009.jpeg",
      "/habitaciones/photos/habitaciones-photo-010.jpeg",
      "/habitaciones/photos/habitaciones-photo-011.jpeg",
      "/habitaciones/photos/habitaciones-photo-012.jpeg",
      "/habitaciones/photos/habitaciones-photo-013.jpeg",
      "/habitaciones/photos/habitaciones-photo-014.jpeg",
      "/habitaciones/photos/habitaciones-photo-015.jpeg",
      "/habitaciones/photos/habitaciones-photo-016.jpeg",
      "/habitaciones/photos/habitaciones-photo-017.jpeg",
      "/habitaciones/photos/habitaciones-photo-018.jpeg",
      "/habitaciones/photos/habitaciones-photo-019.jpeg",
      "/habitaciones/photos/habitaciones-photo-020.jpeg",
      "/habitaciones/photos/habitaciones-photo-021.jpeg",
      "/habitaciones/photos/habitaciones-photo-022.jpeg",
      "/habitaciones/photos/habitaciones-photo-023.jpeg",
      "/habitaciones/photos/habitaciones-photo-024.jpeg",
      "/habitaciones/photos/habitaciones-photo-025.jpeg",
      "/habitaciones/photos/habitaciones-photo-026.jpeg",
      "/habitaciones/photos/habitaciones-photo-027.jpeg",
      "/habitaciones/photos/habitaciones-photo-028.jpeg",
      "/habitaciones/photos/habitaciones-photo-029.jpeg",
      "/habitaciones/photos/habitaciones-photo-030.jpeg",
      "/habitaciones/photos/habitaciones-photo-031.jpeg",
      "/habitaciones/photos/habitaciones-photo-032.jpeg",
      "/habitaciones/photos/habitaciones-photo-033.jpeg",
      "/habitaciones/photos/habitaciones-photo-034.jpeg",
      "/habitaciones/photos/habitaciones-photo-035.jpeg",
      "/habitaciones/photos/habitaciones-photo-036.jpeg",
      "/habitaciones/photos/habitaciones-photo-037.jpeg",
      "/habitaciones/photos/habitaciones-photo-038.jpeg",
      "/habitaciones/photos/habitaciones-photo-039.jpeg",
      "/habitaciones/photos/habitaciones-photo-040.jpeg"
    ],
    "videos": [
      "/habitaciones/videos/habitaciones-video-001.mp4",
      "/habitaciones/videos/habitaciones-video-002.mp4",
      "/habitaciones/videos/habitaciones-video-003.mp4",
      "/habitaciones/videos/habitaciones-video-004.mp4",
      "/habitaciones/videos/habitaciones-video-005.mp4",
      "/habitaciones/videos/habitaciones-video-006.mp4",
      "/habitaciones/videos/habitaciones-video-007.mp4",
      "/habitaciones/videos/habitaciones-video-008.mp4",
      "/habitaciones/videos/habitaciones-video-009.mp4",
      "/habitaciones/videos/habitaciones-video-010.mp4"
    ]
  }
} as const;

export type MediaSection = keyof typeof media;
